apiVersion: edge.kubestellar.io/v1alpha1
kind: PlacementDecision
metadata:
  name: test-placementdecision
spec:
  destinations:
    - clusterId: cluster1
  workload:
    clusterScope:
    - group: ""
      version: v1
      resource: namespaces
      objectNames:
      - nginx
    namespaceScope:
      - group: apps
        version: v1
        resource: deployments
        objectsByNamespace:
          - namespace: nginx
            names:
            - nginx-deployment
