apiVersion: control.kubestellar.io/v1alpha1
kind: Binding
metadata:
  name: my-first-binding
spec:
  destinations:
    - clusterId: cluster1
  workload:
    namespaceScope:
      - group: apps
        version: v1
        resource: deployments
        objectsByNamespace:
          - namespace: default
            names:
            - nginx-deployment
      - group: ""
        version: v1
        resource: serviceaccounts
        objectsByNamespace:
          - namespace: default
            names:
            - my-sa
    workloadGeneration: 2