apiVersion: v1
kind: ServiceAccount
metadata:
  name: transport-controller
  namespace: default
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: transport-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - configmaps
  - events
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: transport-controller
subjects:
- kind: ServiceAccount
  name: transport-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: transport-controller
  apiGroup: rbac.authorization.k8s.io
---